service: sasi-frontend-web

#frameworkVersion: "1.35.1"
plugins:
  - serverless-nextjs-plugin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1
  environment:
    SLS_DEBUG: true

package:
  exclude:
    - ./**
myNextApplication:
  component: "@sls-next/serverless-component@{version_here}"

resources:
  - ${file(assets-pmbplus.yml)}
